# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ip_control_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(141, 297)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(4000, 4000))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_delete = QtWidgets.QPushButton(Form)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 2, 0, 1, 4)
        self.pushButton_graph = QtWidgets.QPushButton(Form)
        self.pushButton_graph.setObjectName("pushButton_graph")
        self.gridLayout.addWidget(self.pushButton_graph, 0, 0, 1, 4)
        self.pushButton_stop = QtWidgets.QPushButton(Form)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.gridLayout.addWidget(self.pushButton_stop, 1, 0, 1, 4)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 7, 3, 3, 1)
        self.lineEdit_threadCount = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_threadCount.sizePolicy().hasHeightForWidth())
        self.lineEdit_threadCount.setSizePolicy(sizePolicy)
        self.lineEdit_threadCount.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_threadCount.setInputMask("")
        self.lineEdit_threadCount.setReadOnly(True)
        self.lineEdit_threadCount.setClearButtonEnabled(False)
        self.lineEdit_threadCount.setObjectName("lineEdit_threadCount")
        self.gridLayout.addWidget(self.lineEdit_threadCount, 11, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 123, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 10, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_delete.setText(_translate("Form", "Sil"))
        self.pushButton_graph.setText(_translate("Form", "Grafik çıkar"))
        self.pushButton_stop.setText(_translate("Form", "Durdur"))
        self.label.setText(_translate("Form", "th-count"))
