# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MonitorNetWorkConnectivity(object):
    def setupUi(self, MonitorNetWorkConnectivity):
        MonitorNetWorkConnectivity.setObjectName("MonitorNetWorkConnectivity")
        MonitorNetWorkConnectivity.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MonitorNetWorkConnectivity)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(509, -1, 291, 581))
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 151, 25))
        self.pushButton.setObjectName("pushButton")
        MonitorNetWorkConnectivity.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MonitorNetWorkConnectivity)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MonitorNetWorkConnectivity.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MonitorNetWorkConnectivity)
        self.statusbar.setObjectName("statusbar")
        MonitorNetWorkConnectivity.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MonitorNetWorkConnectivity)
        self.dockWidget.setBaseSize(QtCore.QSize(0, 0))
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableTarget = QtWidgets.QTableWidget(self.dockWidgetContents)
        self.tableTarget.setObjectName("tableTarget")
        self.tableTarget.setColumnCount(0)
        self.tableTarget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableTarget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MonitorNetWorkConnectivity.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(MonitorNetWorkConnectivity)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MonitorNetWorkConnectivity.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)

        self.retranslateUi(MonitorNetWorkConnectivity)
        QtCore.QMetaObject.connectSlotsByName(MonitorNetWorkConnectivity)

    def retranslateUi(self, MonitorNetWorkConnectivity):
        _translate = QtCore.QCoreApplication.translate
        MonitorNetWorkConnectivity.setWindowTitle(_translate("MonitorNetWorkConnectivity", "MainWindow"))
        self.pushButton.setText(_translate("MonitorNetWorkConnectivity", "Ping Listesi Ekle"))
