# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTDesigns/PingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pingWindow(object):
    def setupUi(self, pingWindow):
        pingWindow.setObjectName("pingWindow")
        pingWindow.resize(593, 526)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(pingWindow)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 30, 321, 311))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(pingWindow)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 17))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(pingWindow)
        self.pushButton.setGeometry(QtCore.QRect(380, 330, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.formLayoutWidget = QtWidgets.QWidget(pingWindow)
        self.formLayoutWidget.setGeometry(QtCore.QRect(340, 30, 274, 316))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBox_byte = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_byte.setMaximum(99999)
        self.spinBox_byte.setProperty("value", 56)
        self.spinBox_byte.setObjectName("spinBox_byte")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.spinBox_byte)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_duration = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_duration.setObjectName("label_duration")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_duration)
        self.spinBox_duration = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_duration.setEnabled(True)
        self.spinBox_duration.setMinimum(1)
        self.spinBox_duration.setMaximum(99999)
        self.spinBox_duration.setObjectName("spinBox_duration")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.spinBox_duration)
        self.pushButton_durationUnlimited = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_durationUnlimited.setCheckable(True)
        self.pushButton_durationUnlimited.setObjectName("pushButton_durationUnlimited")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.pushButton_durationUnlimited)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        self.dateTimeEdit.setEnabled(False)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.dateTimeEdit)
        self.checkBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.checkBox_KillMod = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox_KillMod.setEnabled(True)
        self.checkBox_KillMod.setObjectName("checkBox_KillMod")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox_KillMod)
        self.spinBox_interval = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_interval.setMinimum(500)
        self.spinBox_interval.setMaximum(99999)
        self.spinBox_interval.setObjectName("spinBox_interval")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.spinBox_interval)
        self.spinBox_timeout = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_timeout.setMaximum(99999)
        self.spinBox_timeout.setProperty("value", 300)
        self.spinBox_timeout.setObjectName("spinBox_timeout")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.spinBox_timeout)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.label_4)

        self.retranslateUi(pingWindow)
        self.pushButton_durationUnlimited.clicked['bool'].connect(self.spinBox_duration.setDisabled) # type: ignore
        self.checkBox.toggled['bool'].connect(self.spinBox_duration.setDisabled) # type: ignore
        self.checkBox.toggled['bool'].connect(self.pushButton_durationUnlimited.setDisabled) # type: ignore
        self.checkBox.toggled['bool'].connect(self.dateTimeEdit.setEnabled) # type: ignore
        self.checkBox_KillMod.toggled['bool'].connect(self.spinBox_interval.setDisabled) # type: ignore
        self.checkBox_KillMod.toggled['bool'].connect(self.spinBox_duration.setDisabled) # type: ignore
        self.checkBox_KillMod.toggled['bool'].connect(self.pushButton_durationUnlimited.setDisabled) # type: ignore
        self.checkBox_KillMod.toggled['bool'].connect(self.checkBox.setDisabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(pingWindow)

    def retranslateUi(self, pingWindow):
        _translate = QtCore.QCoreApplication.translate
        pingWindow.setWindowTitle(_translate("pingWindow", "Ping Ekle"))
        self.label.setText(_translate("pingWindow", "Ping Listesi"))
        self.pushButton.setText(_translate("pingWindow", "Add List"))
        self.label_2.setText(_translate("pingWindow", "Ping byteSize"))
        self.label_3.setText(_translate("pingWindow", "Ping interval (ms)"))
        self.label_duration.setText(_translate("pingWindow", "Duration (second)"))
        self.pushButton_durationUnlimited.setText(_translate("pingWindow", "infinit ping"))
        self.dateTimeEdit.setDisplayFormat(_translate("pingWindow", "d.MM.yyyy HH:mm"))
        self.checkBox.setText(_translate("pingWindow", "Tarih "))
        self.checkBox_KillMod.setText(_translate("pingWindow", "Kill Mod"))
        self.label_4.setText(_translate("pingWindow", "time out (ms)"))
