# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pingWindow(object):
    def setupUi(self, pingWindow):
        pingWindow.setObjectName("pingWindow")
        pingWindow.resize(572, 526)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(pingWindow)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 30, 321, 311))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(pingWindow)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 17))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(pingWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(350, 40, 161, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(pingWindow)
        self.pushButton.setGeometry(QtCore.QRect(380, 330, 89, 25))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(pingWindow)
        QtCore.QMetaObject.connectSlotsByName(pingWindow)

    def retranslateUi(self, pingWindow):
        _translate = QtCore.QCoreApplication.translate
        pingWindow.setWindowTitle(_translate("pingWindow", "Ping Ekle"))
        self.label.setText(_translate("pingWindow", "Ping Listesi"))
        self.label_2.setText(_translate("pingWindow", "Ping byteSize"))
        self.label_3.setText(_translate("pingWindow", "Ping interval (ms)"))
        self.pushButton.setText(_translate("pingWindow", "Add List"))
