# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sshClient_summaryi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(408, 70)
        Dialog.setMinimumSize(QtCore.QSize(0, 70))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 70))
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(10, 0, 379, 68))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/ubuntulogo.png"))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_username = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_username.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_username.setReadOnly(True)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout_2.addWidget(self.lineEdit_username)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.lineEdit_hostname = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_hostname.setReadOnly(True)
        self.lineEdit_hostname.setObjectName("lineEdit_hostname")
        self.verticalLayout_3.addWidget(self.lineEdit_hostname)
        self.horizontalLayout.addWidget(self.widget_2)
        self.pushButton_more = QtWidgets.QPushButton(self.splitter)
        self.pushButton_more.setStyleSheet("QPushButton {\n"
"    padding-top: 20px;\n"
"    padding-bottom: 20px;\n"
"    writing-mode: vertical-rl;  /* Sağdan sola dikey yazı */\n"
"    text-orientation: mixed;    /* Harfler yan döner */\n"
"}")
        self.pushButton_more.setObjectName("pushButton_more")
        self.pushButton_close = QtWidgets.QPushButton(Dialog)
        self.pushButton_close.setGeometry(QtCore.QRect(390, 0, 16, 25))
        self.pushButton_close.setObjectName("pushButton_close")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "User Name"))
        self.label_3.setText(_translate("Dialog", "Host Name"))
        self.pushButton_more.setText(_translate("Dialog", "More"))
        self.pushButton_close.setText(_translate("Dialog", "X"))
import resource_rc
