# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTDesigns/targetWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pingWindow(object):
    def setupUi(self, pingWindow):
        pingWindow.setObjectName("pingWindow")
        pingWindow.resize(458, 300)
        self.gridLayout = QtWidgets.QGridLayout(pingWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableTarget = QtWidgets.QTableWidget(pingWindow)
        self.tableTarget.setObjectName("tableTarget")
        self.tableTarget.setColumnCount(12)
        self.tableTarget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableTarget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTarget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTarget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTarget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTarget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTarget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTarget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTarget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTarget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTarget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTarget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTarget.setHorizontalHeaderItem(11, item)
        self.tableTarget.horizontalHeader().setMinimumSectionSize(57)
        self.tableTarget.horizontalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.tableTarget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(pingWindow)
        QtCore.QMetaObject.connectSlotsByName(pingWindow)

    def retranslateUi(self, pingWindow):
        _translate = QtCore.QCoreApplication.translate
        pingWindow.setWindowTitle(_translate("pingWindow", "Ping Window"))
        item = self.tableTarget.horizontalHeaderItem(0)
        item.setText(_translate("pingWindow", "Host Name"))
        item = self.tableTarget.horizontalHeaderItem(1)
        item.setText(_translate("pingWindow", "IP addres"))
        item = self.tableTarget.horizontalHeaderItem(2)
        item.setText(_translate("pingWindow", "New Column"))
        item = self.tableTarget.horizontalHeaderItem(3)
        item.setText(_translate("pingWindow", "Failed Count"))
        item = self.tableTarget.horizontalHeaderItem(4)
        item.setText(_translate("pingWindow", "%Failed"))
        item = self.tableTarget.horizontalHeaderItem(5)
        item.setText(_translate("pingWindow", "New Column"))
        item = self.tableTarget.horizontalHeaderItem(6)
        item.setText(_translate("pingWindow", "Last Ping Status"))
        item = self.tableTarget.horizontalHeaderItem(7)
        item.setText(_translate("pingWindow", "Avarage RTT"))
        item = self.tableTarget.horizontalHeaderItem(8)
        item.setText(_translate("pingWindow", "min RTT"))
        item = self.tableTarget.horizontalHeaderItem(9)
        item.setText(_translate("pingWindow", "max RTT"))
        item = self.tableTarget.horizontalHeaderItem(10)
        item.setText(_translate("pingWindow", "Jitter"))
        item = self.tableTarget.horizontalHeaderItem(11)
        item.setText(_translate("pingWindow", "Last Result"))
